AWSTemplateFormatVersion: "2010-09-09"

Description: "Amazon Linux bastion host based on region with SSH ingress from single parameterized IP"

Parameters:

  VPCID:
    Type: "AWS::EC2::VPC::Id"
    Description: "VPC ID"

  publicsubnet1:
    Type: "AWS::EC2::Subnet::Id"
    Description: "Public Subnet ID"

  KeyPairPrimary1:
    Type: "AWS::EC2::KeyPair::KeyName"
    Default: ""
    Description: "Primary EC2 KeyPair 1"

  InstanceHostName:
    Type: String
    Default: bastion
    Description: Instance hostname.  Can be single word or.multiple.words. Will be instance Name tag.

  InstanceSize1:
    Type: String
    Default: t2.micro
    Description: Instance size of the bastion server

  TagEnvironment:
    Type: String
    Description: Environment type for default resource tagging
    Default: production
    AllowedValues:
      - production
      - staging
      - sandbox
      - test
      - development
      - qa

  TagOwner:
    Type: String
    Description: Owner of the resources.  Person/Department,etc
    Default: ""

  IngressIP1:
    Type: String
    Description: Single IP address ending in /32 for SSH ingress


Metadata:
  AWS::CloudFormation::Interface:
      ParameterGroups:
        - Label:
            default: "Network Settings"
          Parameters:
              - VPCID
              - VPCCidr
              - publicsubnet1
        - Label:
            default: "EC2 Stack Settings"
          Parameters:
            - InstanceHostName
            - InstanceSize1
            - KeyPairPrimary1
            - IngressIP1
        - Label:
            default: "Tagging"
          Parameters:
            - TagEnvironment
            - TagOwner


# Map last updated 10/03/19
Mappings:
  RegionMap:
    us-east-1:
      "azLinAmi": "ami-4fffc834"   # US East (N. Virginia)
    us-east-2:
      "azLinAmi": "ami-ea87a78f"   # US East (Ohio)
    us-west-1:
      "azLinAmi": "ami-3a674d5a"   # US West (N. California)
    us-west-2:
      "azLinAmi": "ami-aa5ebdd2"   # US West (Oregon)
    ca-central-1:
      "azLinAmi": "ami-5ac17f3e"   # Canada (Central)
    eu-west-1:
      "azLinAmi": "ami-ebd02392"   # EU (Ireland)
    eu-central-1:
      "azLinAmi": "ami-657bd20a"   # EU (Frankfurt)
    eu-west-2:
      "azLinAmi": "ami-489f8e2c"   # EU (London)
    eu-west-3:
      "azLinAmi": "ami-0ebc281c20e89ba4b"   # EU (Paris)
    ap-southeast-1:
      "azLinAmi": "ami-fdb8229e"   # Asia Pacific (Singapore)
    ap-southeast-2:
      "azLinAmi": "ami-30041c53"   # Asia Pacific (Sydney)
    ap-northeast-2:
      "azLinAmi": "ami-8663bae8"   # Asia Pacific (Seoul)
    ap-northeast-1:
      "azLinAmi": "ami-4af5022c"   # Asia Pacific (Tokyo)
    ap-south-1:
      "azLinAmi": "ami-d7abd1b8"   # Asia Pacific (Mumbai)
    sa-east-1:
      "azLinAmi": "ami-d27203be"   # South America (Sao Paulo)


Resources:

  sgBastion:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: bastion
      GroupDescription: ingress host for management
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: '6'
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref IngressIP1
      SecurityGroupEgress:
        - IpProtocol: '-1'
          FromPort: '-1'
          ToPort: '-1'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: "Name"
          Value: "bastion"
        - Key: "managed-by"
          Value: cloudformation
        - Key: "environment"
          Value: !Ref TagEnvironment
        - Key: owner
          Value: !Ref TagOwner

  roleBastion:
    Type: "AWS::IAM::Role"
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      RoleName: bastion

  policyCloudWatchLogPut:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "ec2-cloudwatch-writeonly"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              -  "logs:CreateLogGroup"
              -  "logs:CreateLogStream"
              -  "logs:PutLogEvents"
              -  "logs:DescribeLogStreams"
            Resource:
              - "arn:aws:logs:*:*:*"
      Roles:
        - !Ref roleBastion

  instanceProfileBastion:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref roleBastion
      InstanceProfileName: bastion

  ec2Bastion:
    Type: "AWS::EC2::Instance"
    Properties:
      BlockDeviceMappings:
        -
          DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2
            VolumeSize: 20
      DisableApiTermination: false
      EbsOptimized: false
      IamInstanceProfile: !Ref instanceProfileBastion
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", azLinAmi]
      InstanceType: !Ref InstanceSize1
      KeyName: !Ref KeyPairPrimary1
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          GroupSet:
            - !Ref sgBastion
          SubnetId: !Ref publicsubnet1
      Tags:
        - Key: "Name"
          Value: !Ref InstanceHostName
        - Key: "backup"
          Value: "no"
        - Key: "retention"
          Value: "7"
        - Key: "managed-by"
          Value: cloudformation
        - Key: "environment"
          Value: !Ref TagEnvironment
        - Key: owner
          Value: !Ref TagOwner
        - Key: ssm
          Value: yes
      UserData:
          Fn::Base64: !Sub
           - |
             #!/bin/bash
             sed -i s/^HOSTNAME.*/HOSTNAME=${Hostname1}/g /etc/sysconfig/network
             yum -y update
             yum -y install bind-tools htop telnet net-tools vim git wget
             yum -y install https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
             yum -y install awslogs
             wget https://s3.amazonaws.com/privo-public-configuration/awslogs/amazon-linux/awslogs.conf -O /etc/awslogs/awslogs.conf
             chkconfig awslogs on
             sed -i s/us\-east\-1/${AWS::Region}/g /etc/awslogs/awscli.conf
             service awslogs restart
             reboot
           - { Hostname1: !Ref InstanceHostName}


Outputs:

  SSHIngressIP:
    Value: !Ref IngressIP1
    Description: Bastion is allowed SSH ingress from this IP
